# Generated by Django 4.0.6 on 2022-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reklama', models.CharField(max_length=100)),
                ('sarlavha', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100)),
                ('chegirma_narx', models.CharField(max_length=100)),
                ('asl_narx', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
